# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------
# Install dependencies stage
FROM node:16-alpine3.14
WORKDIR /app
COPY package.json ./
#RUN npm install --frozen-lockfile
RUN npm install

COPY . .
RUN npm run build

CMD ["npm","run", "dev"]