import Head from 'next/head'
import { useRouter } from 'next/router';
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    router.push('nx-rider-managment');
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title>NX Rider Managment</title>
        {/* <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY"></script> */}
        {/* <script src={"https://maps.googleapis.com/maps/api/js?sensor=false&key=AIzaSyCoHv5QFJGjvBW8GQmtkxJwYE55_cxXSjI&libraries=geometry,drawing,places"}></script> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
        {/* <script src={"https://maps.googleapis.com/maps/api/js?key=AIzaSyCoHv5QFJGjvBW8GQmtkxJwYE55_cxXSjI&libraries=geometry,drawing,places"}></script> */}


      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to NX Rider Managment
        </h1>
      </main>
    </div >
  )
}
